### PR TITLE
Allow using GET/POST parameter to set redirect URL.

### PR DESCRIPTION
**Pull request by edgimar**
Fixes issue #2:  phpBB will now redirect to the URL specified by the
`redirect` parameter.

### CODE REVIEW

**Review by kasimi — CHANGES_REQUESTED** [review]
`request_var()` is deprecated. Please inject the `request` service and call `$this->request->variable()` instead.

**Comment by edgimar** [comment]
Should be fixed now.

**Comment by kasimi** [comment]
It should be injected via `services.yml`, similar to the `config` service.

**Comment by edgimar** [comment]
Very well... Done.

**Comment by kasimi** [comment]
Looks good, but please remove the `global` statement in the constructor

**Comment by edgimar** [comment]
Oops - it's now removed.

**Review by kasimi — APPROVED** [review]

**Comment by kasimi** [comment]
Thanks!

**Pull request merged**
